version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    # target_branch: dev # TODO uncomment
    update_schedule: weekly
    default_reviewers:
      - blakemorgan # TODO replace
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "security:patch"
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
