version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    # target_branch: dev
    update_schedule: weekly
    default_reviewers:
      - blakemorgan
    automerged_updates:
      - match:
          update_type: "semver:minor"
